import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import { App } from 'supertest/types';
import { AppModule } from './../src/app.module';
import { PrismaService } from './../src/prisma/prisma.service';

interface AuthResponseBody {
  accessToken: string;
}

interface FarmResponseBody {
  id: string;
}

interface EmployeeResponseBody {
  id: string;
  name: string;
  type: string;
  hourlyRate: number;
  totalHours: number;
  balanceHours: number;
  grossCost: number;
  paidCost: number;
  totalCost: number;
}

interface TimeEntryResponseBody {
  id: string;
  hours: number;
}

interface SummaryResponseBody {
  employeeCount: number;
  activeCount: number;
  totalHours: number;
  balanceHours: number;
  totalCost: number;
}

describe('Employees / Equipe (e2e)', () => {
  let app: INestApplication<App>;
  let prisma: PrismaService;

  const owner = {
    email: `employees-owner-${Date.now()}@campoflow.test`,
    password: 'password123',
    name: 'Owner',
  };

  let ownerToken: string;
  let farmId: string;
  let employeeId: string;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        transform: true,
        forbidNonWhitelisted: true,
      }),
    );
    await app.init();
    prisma = app.get(PrismaService);

    const res = await request(app.getHttpServer())
      .post('/auth/register')
      .send(owner);
    ownerToken = (res.body as AuthResponseBody).accessToken;

    const farmRes = await request(app.getHttpServer())
      .post('/fazendas')
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({ name: 'Fazenda Equipe Teste' });
    farmId = (farmRes.body as FarmResponseBody).id;
  });

  afterAll(async () => {
    await prisma.timeEntry.deleteMany({ where: { farmId } });
    await prisma.employee.deleteMany({ where: { farmId } });
    await prisma.membership.deleteMany({ where: { farmId } });
    await prisma.farm.delete({ where: { id: farmId } });
    await prisma.user.deleteMany({ where: { email: owner.email } });
    await app.close();
  });

  it('creates an employee (chapa) with an hourly rate', async () => {
    const res = await request(app.getHttpServer())
      .post(`/fazendas/${farmId}/funcionarios`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({
        name: 'João da Silva',
        type: 'CHAPA',
        role: 'Carregamento',
        hourlyRate: 25,
      })
      .expect(201);

    const body = res.body as EmployeeResponseBody;
    expect(body.name).toBe('João da Silva');
    expect(body.type).toBe('CHAPA');
    expect(body.hourlyRate).toBe(25);
    employeeId = body.id;
  });

  it('records worked hours and computes cost (hours × rate)', async () => {
    await request(app.getHttpServer())
      .post(`/fazendas/${farmId}/funcionarios/${employeeId}/horas`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({ description: 'Carregamento de bezerros', hours: 8 })
      .expect(201);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);

    const body = res.body as EmployeeResponseBody;
    expect(body.totalHours).toBe(8);
    expect(body.balanceHours).toBe(8);
    expect(body.totalCost).toBe(200); // 8 × 25
  });

  it('records a folga (negative hours) that lowers the balance and the owed cost', async () => {
    await request(app.getHttpServer())
      .post(`/fazendas/${farmId}/funcionarios/${employeeId}/horas`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({ description: 'Folga (banco de horas)', hours: -3 })
      .expect(201);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);

    const body = res.body as EmployeeResponseBody;
    expect(body.totalHours).toBe(8); // worked hours unchanged
    expect(body.balanceHours).toBe(5); // 8 - 3 banked balance
    expect(body.grossCost).toBe(200); // value generated by the 8 worked hours
    expect(body.totalCost).toBe(125); // owed: (8 - 3) × 25, folga discounts
  });

  it('exposes the farm-level equipe summary', async () => {
    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/resumo`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);

    const body = res.body as SummaryResponseBody;
    expect(body.employeeCount).toBe(1);
    expect(body.activeCount).toBe(1);
    expect(body.totalCost).toBe(125);
  });

  it('edits a time entry, recomputing derived totals', async () => {
    const detail = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    const workedEntry = (
      detail.body as { timeEntries: TimeEntryResponseBody[] }
    ).timeEntries.find((e) => e.hours === 8)!;

    await request(app.getHttpServer())
      .patch(
        `/fazendas/${farmId}/funcionarios/${employeeId}/horas/${workedEntry.id}`,
      )
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({ hours: 10 })
      .expect(200);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    const body = res.body as EmployeeResponseBody;
    expect(body.totalHours).toBe(10);
    expect(body.grossCost).toBe(250); // 10 × 25 generated
    expect(body.totalCost).toBe(175); // owed: (10 - 3) × 25
  });

  it('deletes a time entry', async () => {
    const detail = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    const folga = (
      detail.body as { timeEntries: TimeEntryResponseBody[] }
    ).timeEntries.find((e) => e.hours === -3)!;

    await request(app.getHttpServer())
      .delete(
        `/fazendas/${farmId}/funcionarios/${employeeId}/horas/${folga.id}`,
      )
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    expect((res.body as EmployeeResponseBody).balanceHours).toBe(10);
  });

  it('marks worked hours as paid, abating them from the owed cost', async () => {
    const detail = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    const worked = (
      detail.body as { timeEntries: TimeEntryResponseBody[] }
    ).timeEntries.find((e) => e.hours === 10)!;

    await request(app.getHttpServer())
      .patch(
        `/fazendas/${farmId}/funcionarios/${employeeId}/horas/${worked.id}`,
      )
      .set('Authorization', `Bearer ${ownerToken}`)
      .send({ paid: true })
      .expect(200);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    const body = res.body as EmployeeResponseBody;
    expect(body.grossCost).toBe(250); // still generated
    expect(body.paidCost).toBe(250); // now settled
    expect(body.totalCost).toBe(0); // nothing owed
  });

  it('deletes the employee', async () => {
    await request(app.getHttpServer())
      .delete(`/fazendas/${farmId}/funcionarios/${employeeId}`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);

    const res = await request(app.getHttpServer())
      .get(`/fazendas/${farmId}/funcionarios`)
      .set('Authorization', `Bearer ${ownerToken}`)
      .expect(200);
    expect((res.body as EmployeeResponseBody[]).length).toBe(0);
  });
});
